<?php

/**
 * @file
 * Contains association.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\user\Entity\User;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

function association_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the association module.
    case 'help.page.association':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('To manage members and persons of the association.') . '</p>';
      return $output;

    default:
  }
}

function association_theme() {
  return [
    'association' => [
      'render element' => 'children',
    ],

    'membership_step0' => [
      'render element' => 'form',
      'template' => 'membership-step0',
    ],
  ];
}

function association_allowed_values_function(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  \Drupal::moduleHandler()
    ->loadInclude('association', 'inc', 'association.allowed.values');

  if ($definition['entity_type'] == 'member') {
    switch ($definition['field_name']) {
      case 'country':
        return association_member_country();
        break;
      case 'status':
        return association_member_status();
        break;
      default:
        break;
    }
  }
}

function association_entity_delete(EntityInterface $entity) {
  $mode = 'delete';
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      _deletePersonsOfMember($entity);
      break;
    case "person":
      // Reset corresponding Member if is Contact
      if ($entity->iscontact->value) {
        $storage = Drupal::entityTypeManager()->getStorage('member');
        $member = $storage->load($entity->member_id->target_id);
        if ($member) {
          $member->set("contact_id", NULL);
          $member->save();
        }
      }
      // Delete the corresponding user
      $user_id = $entity->user_id->target_id;
      $userofperson = User::load($user_id);
      if ($userofperson) {
        $userofperson->delete();
      }
      break;
    default:
  }
  _export_association($entityType);
}

function association_entity_insert(EntityInterface $entity) {
  $mode = 'insert';
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      break;
    case "person":
      break;
    default:
  }
  _export_association($entityType);
}

function association_entity_presave(EntityInterface $entity) {
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      if ($entity->status->value == -1) {
        $entity->designation = t('Member') . sprintf("%03d", $entity->id->value);
        $entity->addresssupplement = NULL;
        $entity->street = NULL;
        $entity->city = NULL;
        $entity->country = NULL;
        $entity->telephone = NULL;
        $entity->status = 0;
        $entity->contact_id = NULL;
        $entity->comment = NULL;
        $entity->owner_id = NULL;
        _deletePersonsOfMember($entity);
      }
      break;
    default:
  }
}

function association_entity_update(EntityInterface $entity) {
  $mode = 'update';
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      /*
       * This code is here to be executed either from Update in CRUD form or from MemberImportStatus
       */
      switch ($entity->status->value) {
        case -2:
          $entity->delete();
          break;
        case 0:
        case 1:
          // List all Persons for this Member
          $id = $entity->id->value;
          $database = Drupal::database();
          $query = $database->select('person', 'ap');
          $query->fields('ap', ['id', 'member_id'])
            ->condition('member_id', $id, '=');
          $results = $query->execute();
          // Deactivate all these Persons
          $storage = Drupal::entityTypeManager()->getStorage('person');
          foreach ($results as $key => $result) {
            $person = $storage->load($result->id);
            $person->set("isactive", 0);
            $person->save();
          }
          break;
        default:
      }
      break;
    case "person":
      if ($entity->isactive->value == 0) {
        //Block the corresponding user
        $user_id = $entity->user_id->target_id;
        $userofperson = User::load($user_id);
        $userofperson->set("status", 0);
        $userofperson->save();
      }
      break;
    default:
  }
  _export_association($entityType);
}

function association_mail($key, &$message, $aParams) {
  $sFrom = Drupal::config('system.site')->get('mail');

  $message['from'] = $sFrom;
  $message['headers'] = [
    'bcc' => $aParams[0],
    'From' => $sFrom,
    'Sender' => $sFrom,
    'Return-Path' => $sFrom,
  ];
  switch ($key) {
    case 'membershipfirstemail':
      $message['subject'] = '[le Jardin de Poissy] Renouvellement d\'adhésion';
      $sBody = "<b>" . $aParams[1] . "</b>";
      $message['body'][] = check_markup(nl2br($sBody), 'full_html');
      break;
    case 'membershipreminderemail':
      $message['subject'] = '[le Jardin de Poissy] Renouvellement d\'adhésion - Relance ' . $aParams[2];
      $sBody = "<b>" . $aParams[1] . "</b>";
      $message['body'][] = check_markup(nl2br($sBody), 'full_html');
      break;
  }
}

function association_menu_local_tasks_alter(&$data, $route_name) {
  $oCurrentUser = Drupal::currentUser();
  switch ($route_name) {
    case 'view.association_members_and_persons.page_1':
    case 'view.association_members.page_1':
    case 'view.association_persons.page_1':
      if ($oCurrentUser->hasPermission('administer users')) {
        $data['tabs'][0]['association.people'] = [
          '#theme' => 'menu_local_task',
          '#link' => [
            'title' => t('Users'),
            'url' => Url::fromRoute('entity.user.collection'),
          ],
          '#weight' => 4,
        ];
      }
      break;
    default:
  }
}

function association_views_pre_render(ViewExecutable $view) {
  switch ($view->id()) {
    case 'association_members':
      switch ($view->current_display) {
        case 'page_1':
          $view->element['#attached']['library'][] = 'association/LoM';
          break;
        default:
      }
      break;
    case 'association_persons':
      switch ($view->current_display) {
        case 'page_1':
          $view->element['#attached']['library'][] = 'association/LoP';
          break;
        default:
      }
      break;
    default:
  }
}

function association_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  switch ($view->id()) {
    case 'association_persons':
      if ($view->current_display == 'page_2') {
        $roles = Drupal::currentUser()->getRoles();
        if (in_array('administrator', $roles)) {
          foreach ($query->where as $condition_group_key => &$condition_group) {
            foreach ($condition_group['conditions'] as $condition_key => &$condition) {
              if ($condition['field'] == 'member_person.status') {
                unset($query->where[$condition_group_key]['conditions'][$condition_key]);
              }
            }
          }
        }
      }
      break;
    default:
  }
}

function _deletePersonsOfMember($entity) {
  // List all Persons for this Member
  $id = $entity->id->value;
  $database = Drupal::database();
  $query = $database->select('person', 'ap');
  $query->fields('ap', ['id', 'member_id'])
    ->condition('member_id', $id, '=');
  $results = $query->execute();
  // Delete all these Persons
  $storage = Drupal::entityTypeManager()->getStorage('person');
  foreach ($results as $key => $result) {
    $person = $storage->load($result->id);
    $person->delete();
  }
}

function _export_association_CSV($view, $page) {
  $view = Views::getView($view);
  $view->setDisplay($page);
  $path = $view->getPath();
  $data = $view->preview($page)['#markup'];
  \Drupal::service('file_system')
    ->saveData($data, 'private://' . $path, FileSystemInterface::EXISTS_REPLACE);
}

function _export_association($entityType) {
  switch ($entityType) {
    case "member":
      _export_association_CSV('association_members', 'rest_export_1');
      _export_association_CSV('association_persons', 'rest_export_3');
      _export_association_CSV('association_members_and_persons', 'rest_export_1');
      break;
    case "person":
      _export_association_CSV('association_persons', 'rest_export_1');
      _export_association_CSV('association_persons', 'rest_export_2');
      _export_association_CSV('association_members_and_persons', 'rest_export_1');
      break;
    default:
  }
}

function _setListOfRecipients($status = 4) {
  $sBcc = '';
  $database = Drupal::database();
  $query = $database->select('member', 'am');
  $query->leftJoin('person', 'ap', 'ap.id = am.contact_id');
  $query->fields('am', ['id', 'status'])->fields('ap', [
    'id',
    'lastname',
    'firstname',
    'email',
  ])->condition('status', $status, '=');
  $results = $query->execute();
  foreach ($results as $key => $result) {
    $sBcc .= $result->email . ", ";
  }
  $sBcc = substr($sBcc, 0, strlen($sBcc) - 2);
  return $sBcc;
}

