<?php

/**
 * @file
 * The Views Send module.
 *
 * Views Send allow mass mailing using Views.
 *
 * @ingroup views_send
 */

const VIEWS_SEND_ID = 'views_send';

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Link;
use Drupal\Core\Mail\MailFormatHelper;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;
use Drupal\filter\Entity\FilterFormat;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\views_send\Event\AllMailAddedEvent;
use Drupal\views_send\Event\MailAddedEvent;
use Drupal\views_send\Event\MailSentEvent;
use Drupal\views_send\Plugin\views\field\ViewsSend;

use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Header\MailboxHeader;

/**
 * E-mail priorities.
 */
define('VIEWS_SEND_PRIORITY_NONE', 0);
define('VIEWS_SEND_PRIORITY_HIGHEST', 1);
define('VIEWS_SEND_PRIORITY_HIGH', 2);
define('VIEWS_SEND_PRIORITY_NORMAL', 3);
define('VIEWS_SEND_PRIORITY_LOW', 4);
define('VIEWS_SEND_PRIORITY_LOWEST', 5);

/**
 * Token pattern.
 */
define('VIEWS_SEND_TOKEN_PATTERN', 'views-send:%s');
define('VIEWS_SEND_TOKEN_PREFIX', '[');
define('VIEWS_SEND_TOKEN_POSTFIX', ']');

/**
 * Gets the selector field if it exists on the passed-in view.
 *
 * @return Drupal\views_send\Plugin\views\field\ViewsSend|false
 *   The field object if found. Otherwise, FALSE.
 */
function _views_send_get_field($view) {
  foreach ($view->field as $field_name => $field) {
    if ($field instanceof ViewsSend) {
      // Add in the view object for convenience.
      $field->view = $view;
      return $field;
    }
  }
  return FALSE;
}

/**
 * Implements the form for the "configure" step.
 */
function views_send_config_form(&$form, &$form_state, $view) {
  $display = $view->storage->id() . ':' . $view->current_display;
  $form['display'] = [
    '#type' => 'value',
    '#value' => $display,
  ];
  $form['from'] = [
    '#type' => 'details',
    '#title' => t('Sender'),
    '#open' => TRUE,
  ];
  $config_basekey = $display . '.uid:' . \Drupal::currentUser()->id();
  $site_config = \Drupal::config('system.site');
  $config = \Drupal::config('views_send.user_settings')->get($config_basekey);
  $form['from']['views_send_from_name'] = [
    '#type' => 'textfield',
    '#title' => t("Sender's name"),
    '#description' => t("Enter the sender's human readable name."),
    '#default_value' => $config['from_name'] ?? $site_config->get('name'),
    '#maxlen' => 255,
  ];
  $form['from']['views_send_from_mail'] = [
    '#type' => 'textfield',
    '#title' => t("Sender's email"),
    '#description' => t("Enter the sender's email address."),
    '#required' => TRUE,
    '#default_value' => $config['from_mail'] ?? $site_config->get('mail'),
    '#maxlen' => 255,
  ];

  $fields = _views_send_get_fields_and_tokens($view, 'fields');
  $tokens = _views_send_get_fields_and_tokens($view, 'tokens');
  $fields_name_text = _views_send_get_fields_and_tokens($view, 'fields_name_text');
  $fields_options = array_merge(['' => '<' . t('select') . '>'], $fields);

  $form['views_send_tokens'] = [
    '#type' => 'value',
    '#value' => $tokens,
  ];

  $form['to'] = [
    '#type' => 'details',
    '#title' => t('Recipients'),
    '#open' => TRUE,
  ];
  $form['to']['views_send_to_name'] = [
    '#type' => 'select',
    '#title' => t("Field used for recipient's name"),
    '#description' => t("Select which field from the current view will be used as recipient's name."),
    '#options' => $fields_options,
    '#default_value' => $config['to_name'] ?? '',
  ];
  $form['to']['views_send_to_mail'] = [
    '#type' => 'select',
    '#title' => t("Field used for recipient's email"),
    '#description' => t("Select which field from the current view will be used as recipient's email."),
    '#options' => $fields_options,
    '#default_value' => $config['to_mail'] ?? '',
    '#required' => TRUE,
  ];
  $form['mail'] = [
    '#type' => 'details',
    '#title' => t('E-mail content'),
    '#open' => TRUE,
  ];
  $form['mail']['views_send_subject'] = [
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#description' => t("Enter the email's subject. You can use tokens in the subject."),
    '#maxlen' => 255,
    '#required' => TRUE,
    '#default_value' => $config['subject'] ?? '',
  ];
  $saved_message = $config['message'] ?? [];
  $form['mail']['views_send_message'] = [
    '#type' => 'text_format',
    '#format' => $saved_message['format'] ?? 'plain_text',
    '#title' => t('Message'),
    '#description' => t('Enter the body of the message. You can use tokens in the message.'),
    '#required' => TRUE,
    '#rows' => 10,
    '#default_value' => $saved_message['value'] ?? '',
  ];
  $form['mail']['token'] = [
    '#type' => 'details',
    '#title' => t('Replacements'),
    '#description' => t('You can use the following tokens in the subject or message.'),
  ];
  if (!\Drupal::moduleHandler()->moduleExists('token')) {
    $form['mail']['token']['tokens'] = [
      '#markup' => views_send_token_help($fields_name_text),
    ];
  }
  else {
    $form['mail']['token'][VIEWS_SEND_ID] = [
      '#type' => 'details',
      '#title' => t('Views Send specific tokens'),
    ];
    $form['mail']['token'][VIEWS_SEND_ID]['tokens'] = [
      '#markup' => views_send_token_help($fields_name_text),
    ];
    $form['mail']['token']['general'] = [
      '#type' => 'details',
      '#title' => t('General tokens'),
    ];
    $token_types = ['site', 'user', 'node', 'current-date'];
    $form['mail']['token']['general']['tokens'] = [
      '#theme' => 'token_tree_link',
      '#token_types' => $token_types,
    ];
  }
  if (\Drupal::service('views_send.mime')->isAvailable() && Drupal::currentUser()->hasPermission('attachments with views_send')) {
    // Set the form encoding type.
    $form['#attributes']['enctype'] = "multipart/form-data";

    // Add a file upload file.
    $form['mail']['views_send_attachments'] = [
      '#type' => 'file',
      '#title' => t('Attachment'),
      '#description' => t("NB! The attached file is stored once per recipient in the database if you aren't sending the message directly."),
    ];
  }

  $form['additional'] = [
    '#type' => 'details',
    '#title' => t('Additional email options'),
  ];
  $form['additional']['views_send_priority'] = [
    '#type' => 'select',
    '#title' => t('Priority'),
    '#options' => [
      VIEWS_SEND_PRIORITY_NONE => t('none'),
      VIEWS_SEND_PRIORITY_HIGHEST => t('highest'),
      VIEWS_SEND_PRIORITY_HIGH => t('high'),
      VIEWS_SEND_PRIORITY_NORMAL => t('normal'),
      VIEWS_SEND_PRIORITY_LOW => t('low'),
      VIEWS_SEND_PRIORITY_LOWEST => t('lowest'),
    ],
    '#description' => t('Note that email priority is ignored by a lot of email programs.'),
    '#default_value' => $config['priority'] ?? 0,
  ];
  $form['additional']['views_send_receipt'] = [
    '#type' => 'checkbox',
    '#title' => t('Request receipt'),
    '#default_value' => $config['receipt'] ?? 0,
    '#description' => t('Request a Read Receipt from your email messages. A lot of email programs ignore these so it is not a definitive indication of how many people have read your message.'),
  ];
  $form['additional']['views_send_headers'] = [
    '#type' => 'textarea',
    '#title' => t('Additional headers'),
    '#description' => t("Additional headers to be send with the message. You'll have to enter one per line. Example:<pre>Reply-To: noreply@example.com\nX-MyCustomHeader: Whatever</pre>"),
    '#rows' => 4,
    '#default_value' => $config['headers'] ?? '',
  ];

  $form['views_send_direct'] = [
    '#type' => 'checkbox',
    '#title' => t('Send the message directly using the Batch API.'),
    '#default_value' => $config['direct'] ?? TRUE,
  ];
  $form['views_send_carbon_copy'] = [
    '#type' => 'checkbox',
    '#title' => t('Send a copy of the message to the sender.'),
    '#default_value' => $config['carbon_copy'] ?? TRUE,
  ];

  $form['views_send_remember'] = [
    '#type' => 'checkbox',
    '#title' => t('Remember these values for the next time a mass mail is sent.'),
    '#default_value' => $config['remember'] ?? FALSE,
  ];
  $query = UrlHelper::filterQueryParameters($_GET, ['q']);
  $url = Url::fromRoute('<current>')->setOption('query', $query);
  $form['actions'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['form-actions']],
    '#weight' => 999,
  ];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Next', [], ['context' => 'views_send: Go to preview']),
    '#validate' => ['views_send_config_form_validate'],
    '#suffix' => Link::fromTextAndUrl(t('Cancel'), $url)->toString(),
  ];

  return $form;
}

/**
 * Validation callback for the "configure" step.
 */
function views_send_config_form_validate($form, &$form_state) {
  $account = Drupal::currentUser();
  $values = $form_state->getValues();
  $build_info = $form_state->getBuildInfo();
  $view = $build_info['args'][0];

  if (!$format = FilterFormat::load($values['views_send_message']['format'])) {
    $form_state->setErrorByName('views_send_message', t('Non-existsing format selected'));
  }
  elseif (!$format->access('use', $account)) {
    $form_state->setErrorByName('views_send_message', t('Illegale format selected'));
  }

  // Check if sender's email is a valid one.
  if (!\Drupal::service('email.validator')->isValid(trim($values['views_send_from_mail']))) {
    $form_state->setErrorByName('views_send_from_mail',
      t("The sender's email is not a valid email address: %mail",
        ['%mail' => $values['views_send_from_mail']]
      )
    );
  }

  // Check in the column selected as email contain valid email values.
  if (!empty($values['views_send_to_mail'])) {
    $wrong_addresses = [];

    $to_mail_field = $values['views_send_tokens'][$values['views_send_to_mail']];
    $selection = $form_state->get('selection');
    foreach ($selection as $row_id) {
      $to_mail = _views_send_strip_html($view->style_plugin->getField($row_id, $to_mail_field));
      $to_mail_arr = explode(',', $to_mail);
      foreach ($to_mail_arr as $to_mail) {
        $to_mail = trim($to_mail);
        if (!\Drupal::service('email.validator')->isValid($to_mail)) {
          $wrong_addresses[$row_id] = $to_mail;
          break;
        }
      }
    }

    if (count($wrong_addresses) > 0) {
      if (count($wrong_addresses) == count($selection)) {
        $error_message = t("The field used for recipient's email contains an invalid email address in all selected rows. Maybe choose another field to act as recipient's email?");
      }
      else {
        $error_message = t("The field used for recipient's email contains an invalid email address in @wrong of @total selected rows. Choose another field to act as recipient's email or return to the view and narrow the selection to a subset containing only valid addresses. Bad addresses:",
          ['@wrong' => count($wrong_addresses), '@total' => count($selection)]
        );
        $error_message .= sprintf('<table><tr><th>%s</th><th>%s</th></tr>',
          t('Row'), t('E-mail address'));
        foreach ($wrong_addresses as $rowid => $wrong_address) {
          $error_message .= sprintf('<tr><td>%s</td><td>%s</td></tr>',
            $rowid, Html::escape($wrong_address));
        }
        $error_message .= '</table>';
      }
      $error_message_as_markup = new FormattableMarkup($error_message, []);
      $form_state->setErrorByName('views_send_to_mail', $error_message_as_markup);
    }
  }
}

/**
 * Implements the form for the "confirm" step.
 *
 * Allows the user to preview the whole message before sending it.
 */
function views_send_confirm_form(&$form, &$form_state, $view) {
  // @todo Set title as #markup in stead.
  $form['#title'] = Html::escape(t('Review and confirm the message that is about to be sent'));

  // Values entered in the "config" step.
  $configuration = $form_state->get('configuration');

  $selection = $form_state->get('selection');

  if (!\Drupal::service('views_send.mime')->isAvailable() && ($configuration['views_send_message']['format'] != 'plain_text')) {
    \Drupal::messenger()->addMessage(t("Only plain text is supported in the message. Any HTML will be converted to text. If you want to format the message with HTML, you need MIME support - for example using the <a href=':url'>Mime Mail</a> module.",
      [':url' => 'https://drupal.org/project/mimemail'])
    );
  }

  // From: parts.
  $from_mail = trim($configuration['views_send_from_mail']);
  $from_name = trim($configuration['views_send_from_name']);

  $form['#attributes']['class'] = ['views-send-preview'];
  $form['from'] = [
    '#type' => 'item',
    '#title' => t('From'),
    '#markup' => '<div class="views-send-preview-value">' .
    Html::escape(_views_send_format_address($from_mail, $from_name, FALSE)) .
    '</div>',
  ];

  $recipients = [];
  $to_name_field = $configuration['views_send_tokens'][$configuration['views_send_to_name']];
  $to_mail_field = $configuration['views_send_tokens'][$configuration['views_send_to_mail']];
  foreach ($selection as $row_id) {
    $to_name = _views_send_strip_html($view->style_plugin->getField($row_id, $to_name_field));
    $to_mail = _views_send_strip_html($view->style_plugin->getField($row_id, $to_mail_field));
    $to_mail_arr = explode(',', $to_mail);
    foreach ($to_mail_arr as $to_mail) {
      $recipients[] = Html::escape(_views_send_format_address($to_mail, $to_name, FALSE));
    }
  }

  $form['to'] = [
    '#type' => 'item',
    '#title' => t('To'),
    '#markup' => '<div id="views-send-preview-to" class="views-send-preview-value">' . implode(', ', $recipients) . '</div>',
  ];
  $form['subject'] = [
    '#type' => 'item',
    '#title' => t('Subject'),
    '#markup' => '<div class="views-send-preview-value">' . Html::escape($configuration['views_send_subject']) . '</div>',
  ];
  $form['message'] = [
    '#type' => 'item',
    '#title' => t('Message'),
    '#markup' => '<div id="views-send-preview-message" class="views-send-preview-value">' . check_markup($configuration['views_send_message']['value'], $configuration['views_send_message']['format']) . '</div>',
  ];

  $headers = [];
  foreach (_views_send_headers($configuration['views_send_receipt'], $configuration['views_send_priority'], $configuration['views_send_from_mail'], $configuration['views_send_headers']) as $key => $value) {
    $headers[] = Html::escape($key . ': ' . $value);
  }

  $form['headers'] = [
    '#type' => 'item',
    '#title' => t('Headers'),
    '#markup' => '<div id="views-send-preview-headers" class="views-send-preview-value">' . implode('<br />', $headers) . '</div>',
  ];
  if (\Drupal::service('views_send.mime')->isAvailable() && !empty($configuration['views_send_attachments']) && Drupal::currentUser()->hasPermission('attachments with views_send')) {
    foreach ($configuration['views_send_attachments'] as $attachment) {
      $attachments[] = Html::escape($attachment->getFilename());
    }
    $form['attachments'] = [
      '#type' => 'item',
      '#title' => t('Attachments'),
      '#markup' => '<div id="views-send-preview-attachments" class="views-send-preview-value">' . implode('<br />', $attachments) . '</div>',
    ];
  }

  $query = UrlHelper::filterQueryParameters($_GET, ['q']);
  $url = Url::fromRoute('<current>')->setOption('query', $query);
  $form['actions'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['form-actions']],
    '#weight' => 999,
  ];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Send', [], ['context' => 'views_send: Send mail']),
    '#suffix' => Link::fromTextAndUrl(t('Cancel'), $url)->toString(),
  ];

  return $form;
}

/**
 * Assembles the email and queues it for sending.
 *
 * Also email sent directly using the Batch API is handled here.
 *
 * @param array $params
 *   Data entered in the "config" step of the form.
 * @param array $selected_rows
 *   An array with the indexes of the selected views rows.
 * @param \Drupal\views\ViewExecutable $view
 *   The actual view objecy.
 */
function views_send_queue_mail($params, $selected_rows, $view) {
  $account = Drupal::currentUser();

  if (!$account->hasPermission('mass mailing with views_send')) {
    \Drupal::messenger()->addError(
      t('No mails sent since you aren\'t allowed to send mass mail with Views. (<a href="@permurl">Edit the permission.</a>)',
        ['@permurl' => Url::fromRoute('user.admin_permissions', [], ['fragment' => 'module-views_send'])->toString()])
    );
    return;
  }

  $formats = filter_formats($account);

  // From: parts.
  $from_mail = trim($params['views_send_from_mail']);
  $from_name = $params['views_send_from_name'];

  $to_mail_key = $params['views_send_tokens'][$params['views_send_to_mail']];
  $to_name_key = $params['views_send_tokens'][$params['views_send_to_name']];
  foreach ($selected_rows as $row_id) {
    $to_mail = _views_send_strip_html($view->style_plugin->getField($row_id, $to_mail_key));
    $to_name = _views_send_strip_html($view->style_plugin->getField($row_id, $to_name_key));

    $subject = $params['views_send_subject'];
    $body = $params['views_send_message']['value'];
    $params['format'] = $params['views_send_message']['format'];

    // This shouldn't happen, but better be 100% sure.
    // FIXME - check disabled by "false".
    if (FALSE && !$formats[$params['format']]->access('use', $account)) {
      \Drupal::messenger()->addMessage(
        t('No mails sent since an illegale format is selected for the message.'));
      return;
    }

    $body = check_markup($body, $params['format']);

    // Populate row/context tokens.
    $token_keys = $token_values = [];
    foreach ($params['views_send_tokens'] as $field_key => $field_name) {
      $token_keys[] = VIEWS_SEND_TOKEN_PREFIX . sprintf(VIEWS_SEND_TOKEN_PATTERN, $field_name) . VIEWS_SEND_TOKEN_POSTFIX;
      $token_values[] = (string) $view->style_plugin->getField($row_id, $field_name);
    }

    // Views Send specific token replacements.
    $subject = str_replace($token_keys, $token_values, $subject);
    $body = str_replace($token_keys, $token_values, $body);

    // Global token replacement, and node/user token replacements
    // if a nid/uid is found in the views result row or is base table.
    $data = [];
    if (property_exists($view->result[$row_id], 'uid')) {
      $uid = $view->result[$row_id]->uid;
    }
    else {
      $uid = (string) $view->style_plugin->getField($row_id, 'uid');
    }
    if ($uid) {
      $data['user'] = User::load($uid);
    }
    if (property_exists($view->result[$row_id], 'nid')) {
      $nid = $view->result[$row_id]->nid;
    }
    else {
      $nid = (string) $view->style_plugin->getField($row_id, 'nid');
    }
    if ($nid) {
      $data['node'] = Node::load($nid);
    }
    $token_service = \Drupal::service('token');
    $subject = $token_service->replace($subject, $data);
    $body = $token_service->replace($body, $data);

    if (!\Drupal::service('views_send.mime')->isAvailable() || (\Drupal::config('mimemail.settings')->get('format') == 'plain_text')) {
      $body = MailFormatHelper::htmlToText($body);
    }
    else {
      // This is needed to avoid escaping of HTML in Swiftmailer.
      $body = Markup::create($body);
    }

    if ($params['format'] == 'plain_text') {
      $plain_format = TRUE;
    }
    else {
      $plain_format = FALSE;
    }

    // We transform receipt, priority in headers,
    // merging them to the user defined headers.
    $headers = _views_send_headers($params['views_send_receipt'], $params['views_send_priority'], $from_mail, $params['views_send_headers']);

    $attachments = !empty($params['views_send_attachments']) ? $params['views_send_attachments'] : [];

    $message = [
      'uid' => $account->id(),
      'timestamp' => time(),
      'from_name' => $from_name,
      'from_mail' => $from_mail,
      'to_name' => $to_name,
      'to_mail' => $to_mail,
      'subject' => _views_send_strip_html($subject),
      'body' => $body,
      'headers' => $headers,
    ];

    if ($params['views_send_direct']) {
      $operations[] = ['views_send_batch_deliver', [$message, $plain_format, $attachments]];
    }
    else {
      _views_send_prepare_mail($message, $plain_format, $attachments);

      // Removing stuff added because some modules don't handle
      // attachments in the format function.
      if (\Drupal::service('views_send.mime')->attachMail()) {
        unset($message['params']);
      }

      // Queue the message to the spool table.
      \Drupal::database()->insert('views_send_spool')->fields($message)->execute();

      $event = new MailAddedEvent($message);
      $event_dispatcher = \Drupal::service('event_dispatcher');
      $event_dispatcher->dispatch($event, MailAddedEvent::EVENT_NAME);
    }
  }

  if ($params['views_send_direct']) {
    if ($params['views_send_carbon_copy']) {
      $message['to_name'] = $from_name;
      $message['to_mail'] = $from_mail;
      $operations[] = ['views_send_batch_deliver', [$message, $plain_format, $attachments]];
    }
    $operations[] = ['views_send_remove_uploaded', [$attachments]];

    $batch = [
      'operations' => $operations,
      'finished' => 'views_send_batch_deliver_finished',
      'progress_message' => t('Sent @current of @total messages.'),
    ];
    batch_set($batch);
    \Drupal::messenger()->addMessage(
      \Drupal::translation()->formatPlural(count($selected_rows), '1 message processed.', '@count messages processed.')
    );
  }
  else {
    if ($params['views_send_carbon_copy']) {
      $message['to_name'] = $from_name;
      $message['to_mail'] = $from_mail;
      \Drupal::database()->insert('views_send_spool')->fields($message)->execute();
    }
    views_send_remove_uploaded($attachments);

    \Drupal::messenger()->addMessage(
      \Drupal::translation()->formatPlural(count($selected_rows),
        '1 message added to the spool.',
        '@count messages added to the spool.')
    );

    $event = new AllMailAddedEvent(count($selected_rows));
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, AllMailAddedEvent::EVENT_NAME);
  }
}

// === Hook implementations ====================================================

/**
 * Implements hook_theme().
 */
function views_send_theme($existing, $type, $theme, $path) {
  return [
    'views_send_select_all' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function views_send_cron() {
  // Load cron functions.
  \Drupal::moduleHandler()->loadInclude(VIEWS_SEND_ID, 'cron.inc');

  // Send pending messages from spool.
  views_send_send_from_spool();

  // Clear successful sent messages.
  views_send_clear_spool();
}

/**
 * Implements hook_mail().
 */
function views_send_mail($key, &$message, $params) {

  // This is a simple message send. User inputs the content directly.
  if ($key == 'direct') {

    // Set the subject.
    $message['subject'] = $params['subject'];

    // Set the body.
    $message['body'][] = $params['body'];

    // Add additional headers.
    $message['headers'] += $params['headers'];
  }

  // @todo Implement node message parsing.
  elseif ($key == 'node') {
    // Translations, theming, etc...
  }
}

// === Helper functions ========================================================

/**
 * Build header array with priority and receipt confirmation settings.
 *
 * @param bool $receipt
 *   True if a receipt is requested.
 * @param int $priority
 *   The message priority.
 * @param string $from
 *   The sender's email address.
 *
 * @return array
 *   Header array with priority and receipt confirmation info
 */
function _views_send_headers($receipt, $priority, $from, $additional_headers) {
  $headers = [];

  // If receipt is requested, add headers.
  if ($receipt) {
    $headers['Disposition-Notification-To'] = $from;
    $headers['X-Confirm-Reading-To'] = $from;
  }

  // Add priority if set.
  switch ($priority) {
    case VIEWS_SEND_PRIORITY_HIGHEST:
      $headers['Priority'] = 'High';
      $headers['X-Priority'] = '1';
      $headers['X-MSMail-Priority'] = 'Highest';
      break;

    case VIEWS_SEND_PRIORITY_HIGH:
      $headers['Priority'] = 'urgent';
      $headers['X-Priority'] = '2';
      $headers['X-MSMail-Priority'] = 'High';
      break;

    case VIEWS_SEND_PRIORITY_NORMAL:
      $headers['Priority'] = 'normal';
      $headers['X-Priority'] = '3';
      $headers['X-MSMail-Priority'] = 'Normal';
      break;

    case VIEWS_SEND_PRIORITY_LOW:
      $headers['Priority'] = 'non-urgent';
      $headers['X-Priority'] = '4';
      $headers['X-MSMail-Priority'] = 'Low';
      break;

    case VIEWS_SEND_PRIORITY_LOWEST:
      $headers['Priority'] = 'non-urgent';
      $headers['X-Priority'] = '5';
      $headers['X-MSMail-Priority'] = 'Lowest';
      break;
  }

  // Add general headers.
  $headers['Precedence'] = 'bulk';

  // Add additional headers.
  $additional_headers = trim($additional_headers);
  $additional_headers = str_replace("\r", "\n", $additional_headers);
  $additional_headers = explode("\n", $additional_headers);
  foreach ($additional_headers as $header) {
    $header = trim($header);
    if (!empty($header)) {
      [$key, $value] = explode(': ', $header, 2);
      $headers[$key] = trim($value);
    }
  }

  return $headers;
}

/**
 * Build a formatted email address.
 */
function _views_send_format_address($mail, $name, $encode = TRUE) {

  // Do not format addres on Windows based PHP systems or when $name is empty.
  if ((substr(PHP_OS, 0, 3) == 'WIN') || empty($name)) {
    return $mail;
  }
  else {
    if ($encode) {
      $mailbox = new MailboxHeader('From', new Address($mail, $name));
      return $mailbox->getBodyAsString();
    }
    return sprintf('"%s" <%s>', $name, $mail);
  }
}

/**
 * Prepare the mail message before sending or spooling.
 *
 * @param array $message
 *   Message array containing the following keys:
 *   from_name
 *     String holding the Sender's name.
 *   from_mail
 *     String holding the Sender's email.
 *   to_name
 *     String holding the Recipient's name.
 *   to_mail
 *     String holding the Recipient's email.
 *   subject
 *     String with the email subject. This argument can be altered here.
 *   body
 *     Text with the email body. This argument can be altered here.
 *   headers
 *     Associative array with email headers. This argument can be altered here.
 * @param bool $plain_format
 *   Whether the email should be sent in plain format.
 * @param array $attachments
 *   An array with file information objects (as returned by file_save_upload).
 */
function _views_send_prepare_mail(&$message, $plain_format = TRUE, $attachments = []) {
  /**
   * @todo In the future, this module will be able to send an existing node.
   * $key will have to make the difference. A value when we pickup a node, other
   * when user inputs the subject & body of the message.
   */
  $key = 'direct';

  // Build message parameters.
  $params = [];
  $params['subject'] = $message['subject'];
  $params['body'] = $message['body'];
  $params['headers'] = $message['headers'];

  if (\Drupal::service('views_send.mime')->isAvailable()) {
    $params['attachments'] = [];
    foreach ($attachments as $attachment) {
      $params['attachments'][] = [
        'filepath' => $attachment->getFileUri(),
        'filename' => $attachment->getFilename(),
        'filemime' => $attachment->getMimeType(),
      ];
    }
    if ($plain_format) {
      // Tell Mimemail module that this is a plain text message
      // as HTML is the default.
      $params['plain'] = TRUE;
    }
  }

  $from_formatted = _views_send_format_address($message['from_mail'], $message['from_name']);

  // Call Drupal standard mail function, but without sending.
  $mail = \Drupal::service('plugin.manager.mail')->mail(VIEWS_SEND_ID, $key,
    $message['to_mail'], \Drupal::languageManager()->getCurrentLanguage()->getId(), $params, $from_formatted, FALSE);

  // Updating message with data from generated mail.
  $message['subject'] = $mail['subject'];
  $message['body'] = $mail['body'];
  $message['headers'] = serialize($mail['headers']);

  // Preserving attachments because some modules don't handle
  // attachments in the format function.
  if (!empty($params['attachments']) && \Drupal::service('views_send.mime')->attachMail()) {
    $attachments = [];
    if (\Drupal::moduleHandler()->moduleExists('mailchimp_transactional')) {
      foreach ($params['attachments'] as $attachment) {
        $attachments[] = [
          'uri' => $attachment['filepath'],
        ];
      }
    }
    elseif (\Drupal::moduleHandler()->moduleExists('swiftmailer')) {
      $attachments = $params['attachments'];
    }

    $message['params'] = ['attachments' => $attachments];
  }
}

/**
 * Sending a prepared message.
 *
 * @return bool
 *   True if the message was sent successfully.
 */
function views_send_deliver($message) {
  if (is_array($message)) {
    $message = (object) $message;

  }

  // See comment about key in _views_send_prepare_mail.
  $key = 'direct';
  $headers = unserialize($message->headers);

  $to_formatted_arr = [];
  foreach (explode(',', $message->to_mail) as $to_mail) {
    $to_formatted_arr[] = _views_send_format_address($to_mail, $message->to_name);
  }
  $to_formatted = implode(', ', $to_formatted_arr);
  $from_formatted = _views_send_format_address($message->from_mail, $message->from_name);
  $mail_arr = [
    'id' => VIEWS_SEND_ID . '_' . $key,
    'module' => VIEWS_SEND_ID,
    'key' => $key,
    'to' => $to_formatted,
    'from' => $from_formatted,
    'subject' => $message->subject,
    'body' => $message->body,
    'headers' => $headers,
    'reply-to' => NULL,
    'send' => TRUE,
    'langcode' => \Drupal::languageManager()->getCurrentLanguage()->getId(),
    'params' => [],
  ];

  // Adding attachments explicitly because some modules don't handle attachments
  // in the format function. NB! Only works for batch delivery of mail.
  if (!empty($message->params) && \Drupal::service('views_send.mime')->attachMail()) {
    $mail_arr['params'] = $message->params;
  }

  $system = \Drupal::service('plugin.manager.mail')->getInstance(['module' => VIEWS_SEND_ID, 'key' => $key]);

  return $system->mail($mail_arr);
}

/**
 * Preparing and sending a message (coming from a batch job).
 */
function views_send_batch_deliver($message, $plain_format, $attachments, &$context) {
  _views_send_prepare_mail($message, $plain_format, $attachments);
  $status = views_send_deliver($message);

  if ($status) {
    if (\Drupal::config('views_send.settings')->get('debug')) {
      \Drupal::logger('views_send')->notice(t('Message sent to %mail.', ['%mail' => $message['to_mail']]));
    }

    $event = new MailSentEvent($message);
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, MailSentEvent::EVENT_NAME);
  }
  else {
    $context['results'][] = t('Failed sending message to %mail - spooling it.',
      ['%mail' => $message['to_mail']]);
    // Queue the message to the spool table.
    \Drupal::database()->insert('views_send_spool')->fields($message)->execute();

    $event = new MailAddedEvent($message);
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, MailAddedEvent::EVENT_NAME);

  }
}

/**
 * Displays status after sending messages as a batch job.
 */
function views_send_batch_deliver_finished($success, $results, $operations) {
  if ($success) {
    foreach ($results as $result) {
      \Drupal::messenger()->addMessage($result);
    }
  }
}

/**
 * Remove uploaded files.
 *
 * @param array $attachments
 *   An array with file entities (coming from file_save_upload).
 */
function views_send_remove_uploaded($attachments) {
  foreach ($attachments as $attachment) {
    $attachment->delete();
  }
}

// === Theming functions =======================================================

/**
 * Theme the replacement tokens.
 *
 * @param array $fields
 *   Keyed array with tokens as keys and description as values.
 *
 * @return string
 *   A themed table with all tokens.
 *
 * @todo Add help for other tokens
 */
function views_send_token_help($fields) {
  $header = [t('Token'), t('Replacement value')];
  $rows = [];
  foreach ($fields as $field => $title) {
    $rows[] = [VIEWS_SEND_TOKEN_PREFIX . sprintf(VIEWS_SEND_TOKEN_PATTERN, $field) . VIEWS_SEND_TOKEN_POSTFIX, $title];
  }
  $table = [
    '#type' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  ];
  $output = \Drupal::service('renderer')->render($table);
  return $output;
}

/**
 * Implements hook_token_info().
 */
function views_send_token_info() {
  $data = [];
  $fields_name_text = _views_send_get_fields_and_tokens(NULL, 'fields_name_text');
  if ($fields_name_text) {
    // We are in the Views form config.
    foreach ($fields_name_text as $field => $title) {
      $data[$field] = [
        'name' => $title,
        'description' => '',
      ];
    }
    $type = [
      'name' => t('Views Send'),
      'description' => t('Tokens for Views Send.'),
      'needs-data' => 'views-send',
    ];
    return [
      'types' => ['views-send' => $type],
      'tokens' => ['views-send' => $data],
    ];
  }
  else {
    foreach (_views_send_email_message_property_info() as $key => $info) {
      $data[$key] = [
        'name' => $info['label'],
        'description' => '',
      ];
    }
    $type = [
      'name' => t('Views Send email message'),
      'description' => t('Tokens for Views Send email message.'),
      'needs-data' => 'views_send_email_message',
    ];
    return [
      'types' => ['views_send_email_message' => $type],
      'tokens' => ['views_send_email_message' => $data],
    ];
  }
}

/**
 * Implements hook_tokens().
 *
 * These token replacements are used by Rules and not in the Views form.
 */
function views_send_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];
  if ($type == 'views_send_email_message' && !empty($data['views_send_email_message'])) {
    foreach ($tokens as $name => $original) {
      $replacements[$original] = $data['views_send_email_message']->{$name};
    }
  }
  return $replacements;
}

/**
 * Generates and returns fields and tokens.
 */
function _views_send_get_fields_and_tokens($view, $type) {
  static $return;
  if (isset($return[$type])) {
    return $return[$type];
  }
  if (!in_array($type, ['fields', 'tokens', 'fields_name_text']) || !$view) {
    return FALSE;
  }
  $fields = [];
  $tokens = [];
  $fields_name_text = [];
  $enable_excluded_fields = $view->field['views_send_bulk_form']->options['enable_excluded_fields'];
  foreach ($view->field as $field_name => $field) {
    // Ignore Views Send field(s).
    if ($field instanceof ViewsSend) {
      continue;
    }
    elseif (isset($field->options['exclude']) && $field->options['exclude']) {
      // If enable_excluded_fields is false, excluded fields should
      // not be available.
      if (!$enable_excluded_fields) {
        continue;
      }
    }
    if (!empty($field->field)) {
      $field_key = $field->field;
    }
    elseif (property_exists($field, 'field_alias')) {
      $field_key = $field->field_alias;
      if ($field_key == 'unknown') {
        $field_key = $field_name;
      }
    }
    else {
      $field_key = $field_name;
    }
    // Add field position to ensure unique keys.
    $field_key .= '_pos_' . $field->position;
    $field_text = $field->label() . ' (' . $field_name . ')';
    $fields[$field_key] = $field_text;
    $tokens[$field_key] = $field_name;
    $fields_name_text[$field_name] = $field_text;
  }

  $return = [];
  $return['fields'] = $fields;
  $return['tokens'] = $tokens;
  $return['fields_name_text'] = $fields_name_text;

  return $return[$type];
}

/**
 * Returns property info for Views Send Email Message.
 */
function _views_send_email_message_property_info() {
  $propertyinfo = [
    'uid' => [
      'type' => 'integer',
      'label' => t('User ID'),
    ],
    'timestamp' => [
      'type' => 'integer',
      'label' => t('Timestamp'),
    ],
    'from_name' => [
      'type' => 'text',
      'label' => t("Sender's name"),
    ],
    'from_mail' => [
      'type' => 'text',
      'label' => t("Sender's email"),
    ],
    'to_name' => [
      'type' => 'text',
      'label' => t("Recipient's name"),
    ],
    'to_mail' => [
      'type' => 'text',
      'label' => t("Recipient's email"),
    ],
    'subject' => [
      'type' => 'text',
      'label' => t('E-mail subject'),
    ],
    'body' => [
      'type' => 'text',
      'label' => t('E-mail body'),
    ],
    'headers' => [
      'type' => 'text',
      'label' => t('E-mail headers (serialized)'),
    ],
  ];
  return $propertyinfo;
}

/**
 * Returns the textual content from a HTML string after stripping.
 *
 * The string is stripped from tags, trimmed and HTML entities decoded.
 *
 * Typically used when handling data from getField that returns HTML (with
 * entities). We have to sanitize the data before using it in headers.
 */
function _views_send_strip_html($html) {
  return html_entity_decode(
    trim(strip_tags($html)), ENT_QUOTES);
}
